services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  mobile:
    build: ./mobile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    environment:
      - PORT=19000
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
